### ISSUE TITLE
Build Separate Docker Images

### ISSUE THREAD

**Issue by douglowe** [UoMResearchIT/wrf-docker#11]
Following the examples of https://stackoverflow.com/questions/36808396/how-to-create-new-docker-image-based-on-existing-image and https://github.com/bioexcel/gromacs-docker it would be good to build multiple docker images, for each of the following tool combinations.

1. WRF + WPS
2. WRF-4DVAR + WRFPLUS
3. WRF-OBSGRID

These should all be based on a root image containing:
- zlib
- hdf5
- netCDF C
- netCDF fortran
- MPICH
- libpng (WRF + WPS only?)
- JasPer (WRF + WPS only?)

**Comment by OliverWoolland** [comment]
This is a great idea - I had vaguely considered it earlier but not had the energy to do it! 

I take it 1a6bbd19041ede69b2d6fd51e91ceae115f91e3f implements this?

**Comment by douglowe** [comment]
Yep - it's implemented in that PR.

Currently set up for local builds. For GROMACS docker the build is run using github actions, and pushing the intermediate images to dockerhub - so that these can be retrieved later for building the final images. Longterm we should probably do this (but for now the local fix is sufficient).
