### ISSUE TITLE
Decide on Hosting Solution for Images

### ISSUE THREAD

**Issue by douglowe** [UoMResearchIT/wrf-docker#9]
We need to link to a hosting location for the generated images. Preferably an institutional location.

**Comment by OliverWoolland** [comment]
At the moment images are hosted at my personal (work) account on [dockerhub](https://hub.docker.com/repository/docker/oliverwoolland/wrf-docker)

It would be much nicer if they were on the UoM Research account somewhere!

**Comment by OliverWoolland** [comment]
Could we maybe use the [github solution](https://docs.github.com/en/packages/working-with-a-github-packages-registry/working-with-the-container-registry)?
